// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package pgdb

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.countNonUniqueStmt, err = db.PrepareContext(ctx, countNonUnique); err != nil {
		return nil, fmt.Errorf("error preparing query CountNonUnique: %w", err)
	}
	if q.readNonUniqueStmt, err = db.PrepareContext(ctx, readNonUnique); err != nil {
		return nil, fmt.Errorf("error preparing query ReadNonUnique: %w", err)
	}
	if q.writeTokenStmt, err = db.PrepareContext(ctx, writeToken); err != nil {
		return nil, fmt.Errorf("error preparing query WriteToken: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.countNonUniqueStmt != nil {
		if cerr := q.countNonUniqueStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countNonUniqueStmt: %w", cerr)
		}
	}
	if q.readNonUniqueStmt != nil {
		if cerr := q.readNonUniqueStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing readNonUniqueStmt: %w", cerr)
		}
	}
	if q.writeTokenStmt != nil {
		if cerr := q.writeTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing writeTokenStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                 DBTX
	tx                 *sql.Tx
	countNonUniqueStmt *sql.Stmt
	readNonUniqueStmt  *sql.Stmt
	writeTokenStmt     *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                 tx,
		tx:                 tx,
		countNonUniqueStmt: q.countNonUniqueStmt,
		readNonUniqueStmt:  q.readNonUniqueStmt,
		writeTokenStmt:     q.writeTokenStmt,
	}
}
