// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package pgdb

import (
	"context"
)

type Querier interface {
	CountNonUnique(ctx context.Context) (int64, error)
	// -- name: BashInsert :exec
	// INSERT INTO token(name, occur)(select * from unnest($1::int[], $2::int[]));
	ReadNonUnique(ctx context.Context, arg ReadNonUniqueParams) ([]ReadNonUniqueRow, error)
	WriteToken(ctx context.Context, name string) error
}

var _ Querier = (*Queries)(nil)
