// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0
// source: query.sql

package pgdb

import (
	"context"
)

const writeToken = `-- name: WriteToken :exec
INSERT INTO token (name) VALUES ($1) 
ON CONFLICT (name) 
DO UPDATE SET occur = token.occur + 1
`

func (q *Queries) WriteToken(ctx context.Context, name string) error {
	_, err := q.exec(ctx, q.writeTokenStmt, writeToken, name)
	return err
}
