// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package pgdb

import (
	"context"
)

type Querier interface {
	WriteToken(ctx context.Context, name string) error
}

var _ Querier = (*Queries)(nil)
